---
name: Geo-GeoPo
version: 0.0.1
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Simple encoder/decoder of GeoPo format
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  Test::Base: 0
  version: 0
provides:
  Geo::Formatter::Format::GeoPo:
    file: lib/Geo/Formatter/Format/GeoPo.pm
    version: 0.0.1
  Geo::GeoPo:
    file: lib/Geo/GeoPo.pm
    version: 0.0.1
generated_by: Module::Build version 0.3
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
